default:
  datapath: "normal_sample.csv"
  destdir: "./normal"
  model: "./class/NormalGenerativeModel.R"

simulation:
  set_seed: 101
  sim_num: 5000
  spcd_w: 0.5
  pi_list:
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 0.9
  sample_list:
    - 60
    - 90
    - 300
    - 600
  rho_list:
    - -0.5
    - -0.3
    - 0
    - 0.3
    - 0.5
  save_dir: "./sim_result"
  
generate:
  set_seed: 101
  generative_model: "./class/NormalGenerativeModel.R"
